/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame2.java
 *
 * Created on Oct 26, 2013, 8:40:19 AM
 */

/**
 *
 * @author SHUBHAM
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /** Creates new form NewJFrame2 */
    public NewJFrame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setText("<<<MANAGEMENT ACCOUNTS>>>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 30, 464, 39);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("FIIGHT PROCESSING");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(480, 100, 140, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("BOOKING DETAILS");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(230, 120, 140, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("FLIGHT DETAILS");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(220, 280, 140, 23);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("EMPLOYEE DETAILS");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(430, 200, 140, 23);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("EXIT");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(700, 190, 70, 23);

        jButton1.setText("NEXT>>>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 310, 250, 40);

        jButton2.setText("LOG OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 310, 290, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/J.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 950, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                if(jRadioButton1.isSelected())
        {
            NewJFrame4 m=new NewJFrame4();
            m.setVisible(true);
            this.setVisible(false);
        }
        else
            if(jRadioButton2.isSelected())
            {
                NewJFrame5 m=new NewJFrame5();
                m.setVisible(true);
                this.setVisible(false);
            }
            else
                if(jRadioButton3.isSelected())
                {
                    NewJFrame6 m=new NewJFrame6();
                    m.setVisible(true);
                    this.setVisible(false);
                }
                else
                    if(jRadioButton4.isSelected())
                    {
                        NewJFrame7 m=new NewJFrame7();
                        m.setVisible(true);
                        this.setVisible(false);
                    }
                    else
                        if(jRadioButton5.isSelected())
                        
                           System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         NewJFrame1 m=new NewJFrame1();
                        m.setVisible(true);
                        this.setVisible(false);


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables

}
